application: masomobana2016
runtime: php55
api_version: 1
version: alpha-001

handlers:
  - url: /.*
    script: index.php

  # To Show the Images Folder
  - url: /images
    static_dir: images

  # To Show the CSS Folder
  - url: /css
    static_dir: css

  # To Show the JS Folder
  - url: /js
    static_dir: js

  - url: /(.*\.(gif|png|jpg))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg)$

  - url: /(.*\.(gif|png|jpg))$
    static_files: images/\1
    upload: images/.*\.(gif|png|jpg)$

  - url: /admin/.*
    script: admin.php
    login: admin

  - url: /.*
    script: 404.php

skip_files:
- ^(node_modules/.*)
